### DISCUSSION TITLE
Installing v4

### DISCUSSION THREAD

**Discussion by definitelyme** [isar-community/isar#105] [Q&A]
Any guide on how to install the community v4?
I tried:
```yaml
dependencies:
  # isar: "3.1.8"
  isar:
    git:
      url: https://github.com/isar-community/isar.git
      path: packages/isar

  # # isar_flutter_libs: "3.1.8"
  # isar_flutter_libs: # contains Isar Core
  #   git:
  #     url: https://github.com/isar-community/isar.git

dev_dependencies:

  # isar_generator: "3.1.0+1"
  isar_generator:
    git:
      url: https://github.com/isar-community/isar.git
      path: packages/isar_generator
```

But i get the error:

```bash
Because every version of isar_generator from git depends on isar from hosted and dexter_health depends on isar from git, isar_generator from git is forbidden.
So, because dexter_health depends on isar_generator from git, version solving failed.
exit code 1
```

I also tried:
```yaml
isar_version: &isar_version 3.1.8

dependencies:
  # isar: "3.1.8"
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

  # isar_flutter_libs: "3.1.8"
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  # isar_generator: "3.1.0+1"
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
```

I get the error:
```bash
Resolving dependencies...
Because dexter_health depends on isar_generator 4.0.0 which doesn't match any versions, version solving failed.
exit code 1
```

How do i specify v4 in `isar_version` at the top
