### ISSUE TITLE
Changed to community version 3.1.1 and get this error

### ISSUE THREAD

**Issue by tschiekdev** [isar-community/isar#4]
IsarError: Could not initialize IsarCore library for processor architecture "android_x64". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
I/flutter ( 5874): Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found

**Comment by vicenterusso** [comment]
Maybe related?

https://github.com/isar/isar/issues/1420

**Comment by mrclauss** [comment]
This is because if you switch to the git source for the package the binaries are missing. Please wait until we published a matching package (containing the binary libraries)

**Comment by mrclauss** [comment]
Until we published it you may give it a try to adapt your pubspec as follows to use the prereleased 3.1.2 version:

```
isar_version : &isar_version ^3.1.2
dependencies:
  isar:
    version: *isar_version
    hosted: https://contactulater.app/
  isar_flutter_libs:
    version: *isar_version
    hosted: https://contactulater.app/
dev_dependencies:
  isar_generator:
    version: *isar_version
    hosted: https://contactulater.app/

```
Please provide some feedback if that works

**Comment by tschiekdev** [comment]
> Until we published it you may give it a try to adapt your pubspec as follows to use the prereleased 3.1.2 version:
> 
> ```
> isar_version : &isar_version ^3.1.2
> dependencies:
>   isar:
>     version: *isar_version
>     hosted: https://contactulater.app/
>   isar_flutter_libs:
>     version: *isar_version
>     hosted: https://contactulater.app/
> dev_dependencies:
>   isar_generator:
>     version: *isar_version
>     hosted: https://contactulater.app/
> ```
> 
> Please provide some feedback if that works

No, I'm sorry. I thought the community version was already ready for use. I need an Isar version that works properly. I don't want to be a "guinea pig" at the moment.

**Comment by vicenterusso** [comment]
> No, I'm sorry. I thought the community version was already ready for use. I need an Isar version that works properly. I don't want to be a "guinea pig" at the moment.

It's ready. It's the same version with only updated dependencies. Check commits history.

Also, try this from another solved issue: https://github.com/isar-community/isar/issues/6#issuecomment-1971879543

**Comment by yuxiaos1132** [comment]
I am also facing this issue. Any updates?

**Comment by yuxiaos1132** [comment]
I am also having this issue. I am using the following packages:

```yaml
  isar: ^3.1.1
  isar_flutter_libs: ^3.1.1

  isar_generator: ^3.1.1
```

I have tried `flutter clean` and reinstalling the app.

The error occurs on a Pixel 3a emulator running Android 14.

The app works fine on a physical device (Pixel 8 Pro).

**Comment by yuxiaos1132** [comment]
I am also having this issue. I am using the following packages:

```yaml
  isar: ^3.1.1
  isar_flutter_libs: ^3.1.1

  isar_generator: ^3.1.1
```

I have tried `flutter clean` and reinstalling the app.

The error occurs on a Pixel 3a emulator running Android 14.

The app works fine on a physical device (Pixel 8 Pro).

**Comment by yuxiaos1132** [comment]
I am also having this issue. I am using the following packages:

```yaml
  isar: ^3.1.1
  isar_flutter_libs: ^3.1.1

  isar_generator: ^3.1.1
```

I have tried `flutter clean` and reinstalling the app.

The error occurs on a Pixel 3a emulator running Android 14.

The app works fine on a physical device (Pixel 8 Pro).
