### ISSUE TITLE
Using v3.1.3 in pubspec leads to an error

### ISSUE THREAD

**Issue by CaptainDario** [isar-community/isar#49]
### Steps to Reproduce

Version solving using this repo seems to fail for me

``` shell
flutter pub get
Resolving dependencies... (1.2s)
Because isar_generator >=3.1.3 <3.1.4 depends on isar from hosted on https://isar-community.dev and database_builder depends on isar from hosted on
  https://pub.isar-community.dev, isar_generator >=3.1.3 <3.1.4 is forbidden.
So, because database_builder depends on isar_generator 3.1.3, version solving failed.
```
My pubspec looks like this

```yaml
isar_version: &isar_version 3.1.3

dependencies:
  xml: ^6.0.0
  path: ^1.8.2
  kana_kit:
    git:
      url: https://github.com/CaptainDario/kana_kit
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  console_bars: ^1.1.0
  tuple: ^2.0.1
  async: ^2.10.0
  compute: ^1.0.2
  archive: ^3.3.2
  csv: ^5.0.2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: any
  isar_generator: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
```

### Details

- Flutter Channel stable, 3.16.9, on macOS 13.5.2 22G91 darwin-arm64
 - Isar version: 3.1.3

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by vicenterusso** [comment]
Try version `3.1.6`

**Comment by CaptainDario** [comment]
This seems to work, is there also a version that makes v4 useable?
4.0.2 does not resolve.

```
Because database_builder depends on isar_generator 4.0.2 which doesn't match any versions, version solving failed.
```

**Comment by vicenterusso** [comment]
Can you post your full pubspec?

**Comment by CaptainDario** [comment]
Yeah sure,

```yaml
name: database_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

isar_version: &isar_version 4.0.2

dependencies:
  xml: ^6.0.0
  path: ^1.8.2
  kana_kit:
    git:
      url: https://github.com/CaptainDario/kana_kit
  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  console_bars: ^1.1.0
  tuple: ^2.0.1
  async: ^2.10.0
  compute: ^1.0.2
  archive: ^3.3.2
  csv: ^5.0.2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: any
  isar_generator: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/

```
