### ISSUE TITLE
linux support not working anymore?

### ISSUE THREAD

**Issue by otmi100** [isar-community/isar#6]
### Steps to Reproduce

Follow the steps in the readme to adopt community version.

### Code sample

```
flutter create -t app isar_linux
cd isar_linux

-> Follow migration guide from readme (only pubspec changes required) 

flutter pub get
dart run build_runner build
flutter build linux

CMake Error at cmake_install.cmake:124 (file):
  file INSTALL cannot find
  "/home/xxx/development/isar_linux/linux/flutter/ephemeral/.plugin_symlinks/isar_flutter_libs/linux/libisar.so":
  No such file or directory.
2

Error: Build process failed
```

### Details

[✓] Flutter (Channel stable, 3.19.2, on Arch Linux 6.7.6-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.19.2 on channel stable at /home/mitch/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (2 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

isar_version: &isar_version 3.1.1
isar*: 
  git:
      url: https://github.com/isar-community/isar.git
      .....

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by vicenterusso** [comment]
Try this:

```yaml
dependency_overrides:
  isar:
    git:
      url: https://github.com/isar-community/isar.git
      ref: 3.1.1

  isar_flutter_libs:
    git:
      url: https://github.com/isar-community/isar.git
      ref: 3.1.1

  isar_generator:
    git:
      url: https://github.com/isar-community/isar.git
      ref: 3.1.1
```

**Comment by mrclauss** [comment]
Probably the same issue like #4 , when fetching isar_flutter_libs from git the binary libraries are not built. Please retry once we published the actual packages...

**Comment by mrclauss** [comment]
Until we published it you may give it a try to adapt your pubspec as follows to use the prereleased 3.1.2 version:

```
isar_version : &isar_version ^3.1.2
dependencies:
  isar:
    version: *isar_version
    hosted: https://contactulater.app/
  isar_flutter_libs:
    version: *isar_version
    hosted: https://contactulater.app/
dev_dependencies:
  isar_generator:
    version: *isar_version
    hosted: https://contactulater.app/

```
Please provide some feedback if that works
