### ISSUE TITLE
isar_flutter_libs 3.1.8 which doesn't match any versions

### ISSUE THREAD

**Issue by UnluckyY1** [isar-community/isar#98]
```
Resolving dependencies...
Because xxx depends on isar_flutter_libs 3.1.8 which doesn't match any versions, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on isar_flutter_libs: flutter pub add isar_flutter_libs:'{"version":"^3.1.7","hosted":"https://pub.isar-community.dev"}'
exit code 1

```

**Comment by UnluckyY1** [comment]
I’ve tried to override the dependency directly from Git, but now iOS builds are failing.

```
isar_flutter_libs: # contains Isar Core
    git:
      url: https://github.com/isar-community/isar.git
      path: packages/isar_flutter_libs
      ref: 8aab130
```

```

Error (Xcode): Undefined symbol: _isar_get_error


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Encountered error while building for device.
```
