### ISSUE TITLE
Unable to resolve dependencies with 4.0.3

### ISSUE THREAD

**Issue by jukka-p** [isar-community/isar#99]
Fetching dependencies currently fail with message
`Because no versions of isar_flutter_libs match 4.0.3 and no versions of isar_flutter_libs match >4.0.3 <5.0.0, isar_flutter_libs ^4.0.3 is forbidden.`

In `pubspec.yml` I have:
```
  isar:
    version: ^4.0.3
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^4.0.3
    hosted: https://pub.isar-community.dev/
```

I think this started with the release of 3.1.8. Same problem as #98 ?
